FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl bash

COPY apps/frontend/package*.json ./
RUN npm install

EXPOSE 5173

CMD ["sh", "-c", "if [ ! -d node_modules/react ]; then npm install; fi && npm run dev -- --host 0.0.0.0 --port 5173"]
